### ISSUE TITLE
LdapPool::get_connection may panic making error handling difficult

### ISSUE THREAD

**Issue by aeveris** [keaz/simple-ldap#10]
Hi, first of all, thank you for this crate!

As it is currently implemented `LdapPool::get_connection` will panic if establishing a connection is unsuccessful, which makes properly handling these kinds of errors difficult.

I would propose to either change this method to return a `Result` or add an alternative method that returns a `Result`, e.g. `try_get_connection`.

If you tell me your preferred solution, I'll gladly take care of the implementation.

**Comment by keaz** [comment]
Hi @aeveris, thank you for opening this issue.
I think changing the existing method to return `Result` is better. We can introduce this with a minor version change.
I assigned this to you.
