### ISSUE TITLE
Error-enum should derive Error

### ISSUE THREAD

**Issue by CmdrSharp** [keaz/simple-ldap#16]
**Is your feature request related to a problem? Please describe.**
Currently, it's very inconvenient to capture errors with for example `thiserror` since the error-type in the crate doesn't derive Error. 

**Describe the solution you'd like**
Perhaps it'd be more ergonomic to use `thiserror` for errors in general; but if not, at least deriving Error would be helpful.

**Describe alternatives you've considered**
The alternative is for users to implement `From<simple_ldap::Error> for Error`, but this breaks easily when/if more error types are added in new releases.

**Comment by keaz** [comment]
@CmdrSharp, Thank you for your request. I raised a PR #17 for this. Please check when you get a chance.

**Comment by CmdrSharp** [comment]
> @CmdrSharp, Thank you for your request. I raised a PR #17 for this. Please check when you get a chance.

Looks much better! I think this'll vastly increase the ergonomics of error handling (both within the lib and as a user of it). Well done!

**Comment by keaz** [comment]
Will you be able to provide approve the PR

**Comment by CmdrSharp** [comment]
Sure thing!
